// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package dba

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFile(ctx context.Context, arg *CreateFileParams) (*File, error)
	CreateNode(ctx context.Context, arg *CreateNodeParams) (*Node, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	GetFileAndNodeInfo(ctx context.Context, id pgtype.UUID) (*GetFileAndNodeInfoRow, error)
	GetFileAuthInfo(ctx context.Context, id pgtype.UUID) (*GetFileAuthInfoRow, error)
	GetJwtInfoByEmail(ctx context.Context, email string) (*GetJwtInfoByEmailRow, error)
}

var _ Querier = (*Queries)(nil)
