// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package dba

import ()

type File struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	ContentType string `json:"contentType"`
	Size        int32  `json:"size"`
	Checksum    string `json:"checksum"`
	NodeId      string `json:"nodeId"`
	UserId      string `json:"userId"`
}

type Node struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Address     string `json:"address"`
	Ssl         bool   `json:"ssl"`
	Capacity    int32  `json:"capacity"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Deleted   bool   `json:"deleted"`
}
