// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package dba

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleADMIN UserRole = "ADMIN"
	UserRoleUSER  UserRole = "USER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"UserRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type File struct {
	ID          string           `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
	Name        string           `json:"name"`
	ContentType string           `json:"contentType"`
	Size        int32            `json:"size"`
	Checksum    string           `json:"checksum"`
	NodeId      string           `json:"nodeId"`
	UserId      string           `json:"userId"`
}

type Node struct {
	ID          string           `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Address     string           `json:"address"`
	Port        int32            `json:"port"`
	Tcp         bool             `json:"tcp"`
	TcpPort     pgtype.Int4      `json:"tcpPort"`
	Ssl         bool             `json:"ssl"`
	Capacity    int32            `json:"capacity"`
}

type User struct {
	ID        string           `json:"id"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	FirstName string           `json:"firstName"`
	LastName  string           `json:"lastName"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Deleted   bool             `json:"deleted"`
	Role      UserRole         `json:"role"`
}
