// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: queries.sql

package dba

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "users" ("id", "firstName", "lastName", "email", "password", "role") VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, "createdAt", "updatedAt", "firstName", "lastName", email, password, deleted, role
`

type CreateUserParams struct {
	ID        string   `json:"id"`
	FirstName string   `json:"firstName"`
	LastName  string   `json:"lastName"`
	Email     string   `json:"email"`
	Password  string   `json:"password"`
	Role      UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Deleted,
		&i.Role,
	)
	return &i, err
}

const getFileUserAndNodeById = `-- name: GetFileUserAndNodeById :one
SELECT "userId", "nodeId" FROM "files" WHERE id = $1
`

type GetFileUserAndNodeByIdRow struct {
	UserId string `json:"userId"`
	NodeId string `json:"nodeId"`
}

func (q *Queries) GetFileUserAndNodeById(ctx context.Context, id string) (*GetFileUserAndNodeByIdRow, error) {
	row := q.db.QueryRow(ctx, getFileUserAndNodeById, id)
	var i GetFileUserAndNodeByIdRow
	err := row.Scan(&i.UserId, &i.NodeId)
	return &i, err
}

const getJwtInfoByEmail = `-- name: GetJwtInfoByEmail :one
SELECT "id", "email", "password", "role", "deleted" FROM "users" WHERE "email" = $1
`

type GetJwtInfoByEmailRow struct {
	ID       string   `json:"id"`
	Email    string   `json:"email"`
	Password string   `json:"password"`
	Role     UserRole `json:"role"`
	Deleted  bool     `json:"deleted"`
}

func (q *Queries) GetJwtInfoByEmail(ctx context.Context, email string) (*GetJwtInfoByEmailRow, error) {
	row := q.db.QueryRow(ctx, getJwtInfoByEmail, email)
	var i GetJwtInfoByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Deleted,
	)
	return &i, err
}

const getNodeById = `-- name: GetNodeById :one
SELECT id, "createdAt", "updatedAt", name, description, address, port, tcp, "tcpPort", ssl, capacity FROM "nodes" WHERE "id" = $1
`

func (q *Queries) GetNodeById(ctx context.Context, id string) (*Node, error) {
	row := q.db.QueryRow(ctx, getNodeById, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.Port,
		&i.Tcp,
		&i.TcpPort,
		&i.Ssl,
		&i.Capacity,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, "createdAt", "updatedAt", "firstName", "lastName", email, password, deleted, role FROM "users" WHERE "email" = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Deleted,
		&i.Role,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, "createdAt", "updatedAt", "firstName", "lastName", email, password, deleted, role FROM "users" WHERE "id" = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Deleted,
		&i.Role,
	)
	return &i, err
}
