// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: queries.sql

package dba

import (
	"context"
)

const getNodeById = `-- name: GetNodeById :one
SELECT id, name, description, address, ssl, capacity FROM "nodes" WHERE "id" = $1
`

func (q *Queries) GetNodeById(ctx context.Context, id string) (*Node, error) {
	row := q.db.QueryRow(ctx, getNodeById, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.Ssl,
		&i.Capacity,
	)
	return &i, err
}
