// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package dba

import (
	"context"
)

type Querier interface {
	GetJwtInfoByEmail(ctx context.Context, email string) (*GetJwtInfoByEmailRow, error)
	GetNodeById(ctx context.Context, id string) (*Node, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id string) (*User, error)
}

var _ Querier = (*Queries)(nil)
