// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package dba

import (
	"context"
)

type Querier interface {
	CreateFile(ctx context.Context, arg *CreateFileParams) (*File, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	GetFileAndNodeInfo(ctx context.Context, id string) (*GetFileAndNodeInfoRow, error)
	GetFileAuthInfo(ctx context.Context, id string) (*GetFileAuthInfoRow, error)
	GetJwtInfoByEmail(ctx context.Context, email string) (*GetJwtInfoByEmailRow, error)
}

var _ Querier = (*Queries)(nil)
